# global configuration file
# this file stores general configuration for ran, along with your global variables, environment overrides and aliases.
# also you CAN'T use variables here.

# whether to ask for interactive prompt on conflicting app query (e.g. if query can refer to 2 or more apps)
# set to true if you want it to fail-fast on conflict without trying to show a dialogue/prompt.
noninteractive = false

# aliases for your apps.
# example:
# hks = "games/silksong"
# song = "silksong"
# ss = "hks" -- yes, you can use aliases to refer to aliases.
[alias]

# custom variables for all of your apps.
# (not environment variables. these are meant to be used in app definition files.)
# example:
# gamepath = "/data/apps/games"
# now you can use $gamepath in your app definition file (in cmds.* fields) to refer to this variable.
[vars]

# global environment variable overrides.
# (global meaning this applies to all apps.
# can be overriden by specific apps or commands, but not by command line environment)
# example:
# WINEPREFIX = "/data/apps/.prefixes/wine_common"
[env]
