name: Build Rust Project

on:
    workflow_call:
    workflow_dispatch:

jobs:
    build:
        runs-on: codeberg-medium
        strategy:
            matrix:
                target:
                    - i686-unknown-linux-gnu
                    - x86_64-unknown-linux-gnu
                    - i686-pc-windows-gnu
                    - x86_64-pc-windows-gnu

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  persist-credentials: false

            - name: Install Rust
              run: |
                  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal
                  echo "$HOME/.cargo/bin" >> $FORGEJO_PATH

            - name: Install cross-compilation deps
              run: |
                  dpkg --add-architecture i386
                  apt update
                  apt install -y \
                    gcc-multilib g++-multilib libc6-dev-i386 \
                    gcc-mingw-w64-i686 gcc-mingw-w64-x86-64

            - name: Install Rust target
              run: rustup target add ${{ matrix.target }}

            - name: Build
              run: cargo build --release --target ${{ matrix.target }}

            - name: Package artifact
              run: |
                  mkdir -p dist
                  BIN_NAME=ran
                  t=${{ matrix.target }}
                  case "$t" in
                    *windows-gnu)
                      BIN="${BIN_NAME}.exe"
                      case "$t" in
                        i686-pc-windows-gnu) ARCH="windows_x86" ;;
                        x86_64-pc-windows-gnu) ARCH="windows_x86_64" ;;
                      esac
                      zip dist/ran_${ARCH}.zip target/$t/release/$BIN
                      ;;
                    *unknown-linux-gnu)
                      BIN="$BIN_NAME"
                      case "$t" in
                        i686-unknown-linux-gnu) ARCH="linux_x86" ;;
                        x86_64-unknown-linux-gnu) ARCH="linux_x86_64" ;;
                      esac
                      chmod +x target/$t/release/$BIN
                      tar -czf dist/ran_${ARCH}.tar.gz -C target/$t/release $BIN
                      ;;
                  esac

            - name: Upload artifact
              uses: forgejo/upload-artifact@v4
              with:
                  name: release-artifacts-${{ matrix.target }}
                  path: dist/*
