name: Build & Release Rust Project

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: codeberg-medium
        uses: ./.forgejo/workflows/build.yml

    release:
        runs-on: codeberg-medium
        needs: build
        permissions:
            contents: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Read version
              id: get_version
              run: |
                  echo "::set-output $(cat version.txt | tr -d " \n\r")"

            - name: Download build artifacts
              uses: actions/download-artifact@v4
              with:
                  pattern: release-artifacts-*
                  path: dist
                  merge-multiple: true

            - name: Create Release
              uses: https://codeberg.org/actions/forgejo-release@v2
              with:
                  tag: ${{ steps.get_version.outputs.version }}
                  title: ${{ steps.get_version.outputs.version }}
                  note-file: release.md
                  draft: true
                  prerelease: false
                  files: dist/*
